import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavigationSidebar from "@/components/sidebar/navsidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-[#f5ffff]">
        <div className="flex flex-row h-screen overflow-hidden">
          <NavigationSidebar />

          <div className="overflow-y-auto flex-1 container">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
